POST http://localhost:3333/api/auth/login
Content-Type: application/json

{"email":"anton.kukharenka@gmail.com","password":"test"}

###
POST http://localhost:3333/api/auth/register
Content-Type: application/json

{
  "email": "anton.kukharenka+1@gmail.com",
  "password": "test"
}
